//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vishalkumarapi.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbladmin
    {
        public int admin_id { get; set; }
        public string admin_name { get; set; }
        public string admin_email_id { get; set; }
        public string admin_password { get; set; }
        public string admin_status { get; set; }
        public string admin_mob_number { get; set; }
        public string user_type { get; set; }
    }
}
