//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vishalkumarapi.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcompany
    {
        public int comp_id { get; set; }
        public string comp_name { get; set; }
        public string comp_email { get; set; }
        public string comp_contact { get; set; }
        public string comp_add { get; set; }
        public string comp_about { get; set; }
        public string comp_password { get; set; }
        public string comp_status { get; set; }
    }
}
